### ISSUE TITLE
Panelized PCB need unique designators when created with KiKit

### ISSUE THREAD

**Issue by casey-zebrowski** [bennymeg/JLC-Plugin-for-KiCad#1]
When a pcb is panelized with KiKit it creates duplicate designators which causes JLC's SMT service to crash.

**Example KiKit**:
kikit panelize ^
    --layout "grid; rows: 3; cols: 1; space: 2mm" ^
    --tabs "fixed; width: 3mm; vcount: 2" ^
    --cuts "mousebites; drill: 0.5mm; spacing: 1mm; offset: 0.2mm; prolong: 0.5mm" ^
    --framing "railstb; width: 3mm; space: 2mm;" ^
    --tooling "3hole; hoffset: 2.5mm; voffset: 1.5mm; size: 1.152mm" ^
    --fiducials "3fid; hoffset: 5mm; voffset: 1.5mm; coppersize: 2mm; opening: 1mm;" ^
    --text "simple; text: JLCJLCJLCJLC; anchor: mt; voffset: 1.5mm; hjustify: center; vjustify: center; height: 1mm; thickness: 0.2mm" ^
    --post "millradius: 1mm" ^
    source.kicad_pcb ^
    /pnl/destination.kicad_pcb

**Fix:** Append duplicate designators with a unique ID in the bom and footprint file
[thread_py.txt](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/8997395/thread_py.txt)
.

**Comment by bennymeg** [comment]
Thanks

**Comment by casey-zebrowski** [comment]
thank you, great stuff.
