### ISSUE TITLE
Getting an error message from JLCPCB

### ISSUE THREAD

**Issue by zapta** [bennymeg/JLC-Plugin-for-KiCad#100]
I just updated to the latest version (3.1.0) and am getting an error when trying to upload to JLCPCB. Any suggestions? As far as I can see the offending components are not in the bom or positions files so I am not sure how JLCPCB know about them (from the gerbers?).

The error message:
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/2184769/01cc92da-36a9-4be4-9dae-78de622ac41e)

The resistors R18 R20 have these attributes:

![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/2184769/75fcbec6-0826-40b9-a8d7-7ba90b6dcf4d)

![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/2184769/8adc835e-fe89-4f82-950e-95fbf3acbb96)

And the test points, which are pads with a single wire, have these attributes:

![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/2184769/6c2d5ba7-d22a-4bbc-b9b6-16337554d2a1)

![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/2184769/e1a9a653-9772-4d08-af70-513e4f4fdf55)

The production files are here:
[heater_2023-11-13_18-47-41.zip](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/13344055/heater_2023-11-13_18-47-41.zip)

**Comment by dzid26** [comment]
Basically you removed them from BOM but they are still in position file. 
To fix you need to exclude from position files in PCB Editor in the Footprint properties:
<img width="582" alt="image" src="https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/841061/487ca736-fa76-4f07-a550-54791025f0a8">
