### ISSUE TITLE
Wrong bottom rotation computation

### ISSUE THREAD

**Issue by set-soft** [bennymeg/JLC-Plugin-for-KiCad#101]
The following computation is wrong:

https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/8db1a4d446336aa4d34d0a66cc8adbae25e3a9d9/plugins/process.py#L207

It only works when the adjust is 0. I see the DB stuff is disabled in the code, so I don't know if you really want to fix it. The problem is that when fixing it people that already added manual rotations for components in the bottom side will get a different rotation.

It took me a while to figure out that the correct rotation is computed using: 

```
(180 - KiCad_Angle) + JLCPCB_Rotation
```

And not:

```
180 - (KiCad_Angle + JLCPCB_Rotation)
```

I also had a wrong rotation in my code (KiBot) and now I fixed it and verified the rotations on JLCPCB, so I don't really need it fixed, but I wanted to explain you what's wrong in your plugin.

**Comment by bennymeg** [comment]
I'm not sure I understand, `∓` are commutative.
Could you correct this line to the appropriate rotation?
https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/8db1a4d446336aa4d34d0a66cc8adbae25e3a9d9/plugins/process.py#L207

**Comment by set-soft** [comment]
> I'm not sure I understand, `∓` are commutative.

Nope, take a look at this:

```
(180 - KiCad_Angle) + JLCPCB_Rotation = 180 - KiCad_Angle + JLCPCB_Rotation
```

And not:

```
180 - (KiCad_Angle + JLCPCB_Rotation) = 180 - KiCad_Angle - JLCPCB_Rotation
```

> Could you correct this line to the appropriate rotation?

You can't just correct this line because you already added `rotation_offset`. You should do it before adding the correction angle. What you need to do is to just undo the KiCad bottom mirroring, then apply the correction angle.

I suggest trying something like this: 
[test.zip](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/13377407/test.zip)

Generate the BoM and CPL and upload it to JLCPCB. I'm getting correct rotations and positions with the following files: 
[JLCPCB_position_bom_jlc.csv](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/13377420/JLCPCB_position_bom_jlc.csv) and [JLCPCB_position_cpl_jlc.csv](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/13377425/JLCPCB_position_cpl_jlc.csv)

Note that J1 to J6 also needs offset adjusts.

**Comment by set-soft** [comment]
> I wonder if this used to be treated differently by JLC.

Most probably, they changed at least twice

**Comment by dzid26** [comment]
I think the calculation should be like this:
https://github.com/Springer-Electronics/JLC-Plugin-for-KiCad/commit/33cec19b258c0aa36e3040cf5bdf3b9db1a3cc64

I applied offset with negative sign to match JLC button behavior (rotate clockwise corresponds to +90deg rotation offset now). 
<img width="119" alt="image" src="https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/841061/bfec17f5-e290-4b81-8492-9aee97938979">
I believe this breaks compatibility with a lot of existing designs, so I am thinking to go back to inverted behaviour.  I just would want to get an agreement on this. 



With that, I took your example above and tested the change and used following offsets:
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/841061/d8a349c7-8b88-44f8-9a93-9ce30a20f4c3)
![capture-2024-01-10T17_50_15 430Z](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/841061/f9542785-452e-44cd-ba28-fdce46ae2412)
![capture-2024-01-10T17_50_25 367Z](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/841061/4d82d1de-f9ed-44ae-bd30-7d0244110355)

It's all good now on both sides.

**Comment by set-soft** [comment]
> I believe this breaks compatibility with a lot of existing designs, so I am thinking to go back to inverted behaviour. I just would want to get an agreement on this.

IMHO compatibility is better than matching the UI sign. You just need to document it.

**Comment by dzid26** [comment]
> > I believe this breaks compatibility with a lot of existing designs, so I am thinking to go back to inverted behaviour. I just would want to get an agreement on this.
> 
> IMHO compatibility is better than matching the UI sign. You just need to document it.

Ok, agreed. This seems consistent with [readme](https://github.com/bennymeg/JLC-Plugin-for-KiCad?tab=readme-ov-file#-offset-component-rotation) which suggest counterclockwise for positive values. 
> ...add an 'JLCPCB Rotation Offset' field with an counter-clockwise orientation offset in degrees to correct...

I will test it a bit more to get position offset consistently applied at the bottom layer.

Btw, the through-hole components need to be have anchor in the center. I created separate [fix](https://github.com/Springer-Electronics/JLC-Plugin-for-KiCad/commit/41b8c694170c2cf5561357f859c97601ae6f5508) for that and I think this one is worth the incompatibility of some old designs.

**Comment by dzid26** [comment]
I believe this is the right way to do it - https://github.com/Springer-Electronics/JLC-Plugin-for-KiCad/commit/73062eab54663557ec8e945dc2106d70a7d48fc9
At this point I was just doing trial and error approach to achieve offsets consistency top/bottom. It's a bit weird but behaves consistent . 

I believe this keeps compatibility for existing designs for top components rotations-offsets. Of course bottom rotation offsets and also position offsets will behave differently for existing designs. 

[test.zip](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/13904319/test.zip)
