### ISSUE TITLE
Optionally Tent Vias

### ISSUE THREAD

**Issue by Zerick** [bennymeg/JLC-Plugin-for-KiCad#108]
Is there a way to select tented vs untented vias?
If not, I would like one.

Thanks!

**Comment by Zerick** [comment]
I did find a work around. If one skips step 3 this tool will default to the last style generated rather than the setting in the Gerber generation wizard.

1 One must check that vias are either tented or not as you wish on Gerber Generation!!!
2 If you want the OTHER option, set it in the gerber generation wizard
3 then you MUST manually generate gerbers ONE time for KiCAD to save this setting <-this is so strange
4 now verify that the plugin is generating gerbers correctly as you wish them (vias tented or not)
5 one only need check the vias on the mask layers to confirm

**Comment by dzid26** [comment]
I think you can use this, simply:
<img width="762" alt="image" src="https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/841061/841cacd4-4b27-4eb7-a2ff-10368765354a">
