### ISSUE TITLE
Any chance of a way to ignore through hole from output?

### ISSUE THREAD

**Issue by virtual812** [bennymeg/JLC-Plugin-for-KiCad#11]
I see there is a way to do this per item, but this could become tedious.

Vanilla KiCad has a option to ignore through hole from production files, is this something that can be done in the plugin?

**Comment by bennymeg** [comment]
I might add a feature to output only THT/SMT in the future.
For now, You will have to ignore the manually.

**Comment by virtual812** [comment]
Thanks mate, that would be appreciated.
Great plugin by the way!

**Comment by dhaillant** [comment]
Maybe, if there's no JLC/LCSC Part Number present in BOM (or if explicit DNP or similar value in JLC/LCSC field), then, it would be interesting to remove those components from all fabrication outputs.
Thanks!
