### ISSUE TITLE
KiCad 8.0.0-rc1 API changed

### ISSUE THREAD

**Issue by akakoziqi** [bennymeg/JLC-Plugin-for-KiCad#112]
In the 8.0.0-rc1 version of KiCad, there is an API change.

When I use this plugin in KiCad 8.0.0-rc1, there is an error:
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/69710421/8c2eff05-0fcf-4d35-aec2-f8554aa882ce)

The reason is footprint object in process.py has no ```HasProperty``` and ```GetProperty``` function. 
I replace the ```HasProperty``` function by ```HasFieldByName``` function, and replace the ```GetProperty``` function by ```GetFieldByName``` function.

Then it seems worked.

But I don't know how to make if capable for the previous version of Kicad. :)

**Comment by boromyr** [comment]
@akakoziqi it worked thanks

**Comment by bennymeg** [comment]
Thanks for letting us know, a solution had already implemented here: [#109].
Will be released in the next major release (v4).
