### ISSUE TITLE
Object has no attribute 'HasProperty'

### ISSUE THREAD

**Issue by biologist79** [bennymeg/JLC-Plugin-for-KiCad#114]
Hi,
just installed KiCad RC2 and tried to run Fabrication Toolkit v3.1.0. 
However, I was shown:

'FOOTPRINT' object has no attribute 'HasProperty'

I'm running KiCad on a Mac M1pro with Mac OS 14.3
Any suggestions?

**Comment by bennymeg** [comment]
KiCad 8 will be supported in v4. Please use older version until then.
