### ISSUE TITLE
BOM and Designators

### ISSUE THREAD

**Issue by catalinalb** [bennymeg/JLC-Plugin-for-KiCad#116]
Good day, 

I am running KiCad 7.0.7
I noticed that it is exporting the designators in a separate file not included into the BOM.

I don´t understand why is the case since JLCPCB asks for BOM and CPL (positions) file.

How can this be fixed? I try to order something.... 

Thank you

**Comment by harbaum** [comment]
For JLCPCB you don't need the designators. You just need the gerber.zip and then bom.csv for the BOM and positions.csv for the CPL. That's it.
