### ISSUE TITLE
Won´t export LCSC Part #

### ISSUE THREAD

**Issue by catalinalb** [bennymeg/JLC-Plugin-for-KiCad#118]
Good day,

I have KiCad 7.0.7 (also try on 7.10 with same results) I did add the LCSC Part # for the first component and try the plugin and it did exported the number. Of course after finishing all the componets in the schematic I got an empty cell. No LCSC numbers.... 

What have I done wrong? 

![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/24923533/7e08fec9-b8ff-47d3-8e5a-ea6554f451d0)
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/24923533/2852e9b2-918c-4df4-965d-647ee311f26c)

**Comment by bennymeg** [comment]
Did you synchronized the schematic with the board after you defined all the MPN's?

**Comment by catalinalb** [comment]
Do you mean to annotate ?
yes I did that....

now it won´t generate the gerber archive .... :(

**Comment by bennymeg** [comment]
No, I mean update, __F8__

**Comment by catalinalb** [comment]
Indeed, it works now! Thank you so much for this ! 
I did know that I had to annotate but didn´t know about the F8 update.

It works now! 

Ticket can be closed!
