### ISSUE TITLE
Kicad 8 - strange error

### ISSUE THREAD

**Issue by rozrabiak** [bennymeg/JLC-Plugin-for-KiCad#119]
Hi, when exporting pcb using plugin I have below error.
How to find what footprint?
Or what can I do?

![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/73905882/d81dcf86-24a2-41c0-8cd5-67404107f9ce)

**Comment by bennymeg** [comment]
Duplicate (#109, #112, #114).
