### ISSUE TITLE
Some parts do not seem to obey the JLCPCB Rotation Offset..

### ISSUE THREAD

**Issue by frohro** [bennymeg/JLC-Plugin-for-KiCad#121]
I cannot find any typos, but some parts do not rotate properly.  Others do just fine with the addition of the field JLCPCB Rotation Offfset and the values in degrees.  I'm not sure why.  Two of my ICs on the lower right of my board do not change orientation with any value in the rotation offset field of the schematic editor when I look at the JLCPCB preview.  The Chat helpers don't seem to put much stock in the preview, but changing the rotation by hand editing the placement file rotates things, so I don't think that is the problem.

**Comment by harbaum** [comment]
You could take a look at the generated positions.csv. It's an ASCII file and you should see the rotation values arriving there in the 4th column.

**Comment by bennymeg** [comment]
press F8 to update the board properties from schematic.

**Comment by tavdog** [comment]
This is happening to me too.  
<img width="971" alt="Screenshot 2024-03-05 at 12 10 14 PM" src="https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/8324295/ab5598dc-9a3e-4f1e-a6a1-4c0852eb05db">

**Comment by harbaum** [comment]
Did you try to debug or fix it as described in previous replies? Do the rotation values show up in the location file? Did you update via f8?

**Comment by tavdog** [comment]
I managed to git it working by using the other jlcpcb plugin which allowed me to manually set the rotation for the parts in question.
