### ISSUE TITLE
Needs Update for KiCad 8.0

### ISSUE THREAD

**Issue by John-Lluch** [bennymeg/JLC-Plugin-for-KiCad#124]
Since Kicad 8.0 this seems to be broken. It stops with an error message:
 'FOOTPRINT' object has no attribute 'HasProperty'

Thanks

**Comment by John-Lluch** [comment]
Edit. I saw reportedly this will be fixed in version 4.0. Not released yet. I'll wait

**Comment by AEFeinstein** [comment]
Seconded!

**Comment by AEFeinstein** [comment]
Thanks!
