### ISSUE TITLE
KiCAD8 compatibility issues

### ISSUE THREAD

**Issue by greenscreenflicker** [bennymeg/JLC-Plugin-for-KiCad#127]
Plugin doesn't work under KiCAD8. It gives the following error msg:
![grafik](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/17407241/7390e67f-e056-49c0-a45d-d40d9635e560)

**Comment by greenscreenflicker** [comment]
That was quick. Can you advise how to update?

**Comment by bennymeg** [comment]
Install v4.0.0 manually from the releases section.
