### ISSUE TITLE
crashing on KiCAD8.99

### ISSUE THREAD

**Issue by danielchisholm** [bennymeg/JLC-Plugin-for-KiCad#129]
On KiCAD 8.99, with Release JLC-Plugin-for-KiCad 4.0.0, crashes once "Generate" button is pushed

starting kicad-nightly from command-line, sometimes this is the output:

<pre>
Xlib: sequence lost (0x22ba9 > 0x12bab) in reply type 0x0!
Trace/breakpoint trap (core dumped)
</pre>

and sometimes:
<pre>
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
kicad: ../../src/xcb_io.c:730: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
</pre>

KiCAD version information:
------

Application: KiCad PCB Editor x86_64 on x86_64

Version: 8.99.0-unknown-0314540fdb~177~ubuntu22.04.1, release build

Libraries:
	wxWidgets 3.2.1
	FreeType 2.11.1
	HarfBuzz 2.7.4
	FontConfig 2.13.1
	libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16

Platform: Linux Mint 21.2, 64 bit, Little endian, wxGTK, X11, cinnamon, x11

Build Info:
	Date: Feb 28 2024 18:06:28
	wxWidgets: 3.2.1 (wchar_t,wx containers) GTK+ 3.24
	Boost: 1.74.0
	OCC: 7.6.3
	Curl: 7.81.0
	ngspice: 42
	Compiler: GCC 11.4.0 with C++ ABI 1016

Build settings:

**Comment by bennymeg** [comment]
Please see #132
