### ISSUE TITLE
Kicad 8.99 does crash

### ISSUE THREAD

**Issue by robouden** [bennymeg/JLC-Plugin-for-KiCad#132]
With Application: KiCad Version: 8.99.0-unknown-cd27f801f6~177~ubuntu22.04.1

When starting the plugin, it crashes KiCad.
PCWway plugin has similar issue with KiCad 8.99, and they have revolved. Maybe if the team from the JLCPCB plugin fabrication tool kit can look how the other team ([Link](https://github.com/pcbway/PCBWay-Plug-in-for-Kicad)) implemented some simple changes with their plugin for KiCad V8.99, that would help, I hope. 

I love to get this plugin working like the PCBWay plugin work snow with KiCad.

Warm Regards,
Rob Oudendijk

**Comment by bennymeg** [comment]
I am not planning to support nightly versions of KiCad.

I have checked the link and did not see any major change.
I have added a patch to hopefully fix the issue, but if it would not, I will address it once the stable release of KiCad 9 will be released.

**Comment by robouden** [comment]
I downloaded the master zip file and tried to add it as the plugin. Tried to install it but get install error.
What to do?

![Screenshot from 2024-03-01 18-06-13](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/1387190/6b73499c-c7f8-4143-85ed-290450dfdaae)

**Comment by bennymeg** [comment]
Download the 4.1.0 release and replace (in the zip) the utils.py file with the new one from master

**Comment by danielchisholm** [comment]
> Download the 4.1.0 release and replace (in the zip) the utils.py file with the new one from master

Thanks Benny.  4.1.0 still crashed, but manually putting in utils.py from 0917e9f worked for me.

**Comment by bennymeg** [comment]
Fixed in 4.2.0
