### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by xzf16** [bennymeg/JLC-Plugin-for-KiCad#133]
When I using fabrication toolkit, I got an error message: Index out of range.
<img width="421" alt="Indexoutofrange" src="https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/34883968/f3bcffb0-8bdc-4360-b561-30bd2027fda5">

Kicad version is:
Application: KiCad PCB Editor x64 on x64

Version: 8.0.0, release build

Libraries:
	wxWidgets 3.2.4
	FreeType 2.12.1
	HarfBuzz 8.3.0
	FontConfig 2.14.2
	libcurl/8.5.0-DEV Schannel zlib/1.3

Platform: Windows 11 (build 22631), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Feb 23 2024 02:24:15
	wxWidgets: 3.2.4 (wchar_t,wx containers)
	Boost: 1.83.0
	OCC: 7.7.1
	Curl: 8.5.0-DEV
	ngspice: 42
	Compiler: Visual C++ 1936 without C++ ABI

Build settings:

Fabarication toolkit version is:4.2.0

**Comment by dzid26** [comment]
Strange, I also am getting this now on a simplest board possible, while it still works on a super complicated one. 
I have a feeling it's related to layer I imported from altium. 
[ford_q3.zip](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/14500137/ford_q3.zip)

**Comment by xzf16** [comment]
> Strange, I also am getting this now on a simplest board possible, while it still works on a super complicated one. I have a feeling it's related to layer I imported from altium. [ford_q3.zip](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/14500137/ford_q3.zip)

The board I have was designed by KiCAD originally, so I don't think it's related to importing from altium issue.

And the board was my companies product, so I can't upload it here.

**Comment by Tjookum** [comment]
I have the exact same issue since updating to kicad 8.

**Comment by bennymeg** [comment]
Can you find what's common on the PCB's that does not work?

**Comment by dzid26** [comment]
> Same Problem here. Can´t Upload PCB, because it´s Product from my Company

I know the problem. 

If you need to fix it immediately, find graphics that are set as "unspecified" (for example graphics) and Exclude from Position files. 
<img width="757" alt="image" src="https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/841061/5b13a85c-38b3-4062-9c6e-925f25f7cd09">
