### ISSUE TITLE
Output files do not follow JLCPCB recommendations

### ISSUE THREAD

**Issue by arxwtf** [bennymeg/JLC-Plugin-for-KiCad#140]
JLCPCB's Help Center contains an [article about preferred settings for generated Gerbers and drill files](https://jlcpcb.com/help/article/362-how-to-generate-gerber-and-drill-files-in-kicad-7).

I noticed these discrepancies between plugin outputs and JLCPCB recommendations (there might be others):

1. [Plugin uses .gbr file extensions](https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/266eb3bd31ecf434a0b696e81c1881899efe30cf/plugins/process.py#L62). JLC prefers Protel file extensions. 
2. [Plugin uses AUX origin (also called "use drill/place file origin")](https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/266eb3bd31ecf434a0b696e81c1881899efe30cf/plugins/process.py#L63). JLC prefers absolute file origin.
3. [Drill file also uses AUX origin.](https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/266eb3bd31ecf434a0b696e81c1881899efe30cf/plugins/process.py#L99)
4. [Drilling: "minimal header" is set to true](https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/266eb3bd31ecf434a0b696e81c1881899efe30cf/plugins/process.py#L98). Screenshot in JLC article has this set to false.
5. [Drill units are set to "imperial"](https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/266eb3bd31ecf434a0b696e81c1881899efe30cf/plugins/process.py#L101). JLC prefers "metric"
6. [Drill map files are not generated (third argument is False)](https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/266eb3bd31ecf434a0b696e81c1881899efe30cf/plugins/process.py#L102). JLC recommends generating drill map files. Map file format should be Gerber (see [SetMapFileFormat -> PLOT_FORMAT_GERBER](https://docs.kicad.org/doxygen/classEXCELLON__WRITER.html#a215553b4b38f976bacc890b6a0290a07)).

~Also, it would be nice if the option "Do not tent vias" could be chosen by plugin user before plotting (by a checkbox, like "Exclude DNP components" is chosen now).~

Thank you for this handy plugin!

**Edit:** after further inspection, I think the absolute / AUX origin doesn't really matter as long as they are the same for gerbers, drill files and position file - which they are now.

**Edit 2:** I noticed that "do not tent vias" from plot settings is respected, so I guess that's a good solution too.

**Comment by bennymeg** [comment]
Thank you for the elaborated explanation.
Would you be willing to submit a PR for these issues?
