### ISSUE TITLE
No subfolder in production

### ISSUE THREAD

**Issue by Schildkroet** [bennymeg/JLC-Plugin-for-KiCad#143]
Hello,

in previous versions, the plugin created a subfolder in production folder like:
`/production/Project_date_time/<files>`

Now all files are just placed in production folder.
How can i restore the previous behaviour?

**Comment by bennymeg** [comment]
Yes, use v3

**Comment by G-glop** [comment]
I'd say this is a non-answer. KiCad doesn't support multiple boards per project, and each project should have its own directory. Thus files without a project specific name are _fine_, but they really should include the project name to avoid confusion. For example the other JLCPCB plugin suffers from the same oversight (Bouni/kicad-jlcpcb-tools#339).
