### ISSUE TITLE
Add information to output file names

### ISSUE THREAD

**Issue by dhaillant** [bennymeg/JLC-Plugin-for-KiCad#15]
Hello,
It would be great to have the output file names include some information (like InteractiveHTMLBom does for example):
the name of the project, the revision number, the date of revision, the date of creation, etc.
Thank you!

**Comment by bennymeg** [comment]
Sound good.
- [Implementation Reference 1](https://github.com/openscopeproject/InteractiveHtmlBom/blob/31b20f84c81b35d5ed3bee7f189536eeff678a7f/InteractiveHtmlBom/core/ibom.py#L222-L235)
- [Implementation Reference 2](https://github.com/openscopeproject/InteractiveHtmlBom/blob/31b20f84c81b35d5ed3bee7f189536eeff678a7f/InteractiveHtmlBom/ecad/kicad.py#L687-L698)

**Comment by dhaillant** [comment]
Hello, is there any progress on this enhancement?
Or is there a config file where one can set the name (and the directory) of the output files?
Thank you.

**Comment by fi0** [comment]
adding board dimensions will be great too.
