### ISSUE TITLE
All output files into the ZIP

### ISSUE THREAD

**Issue by tormyvancool** [bennymeg/JLC-Plugin-for-KiCad#17]
I noticed that the .ZIP file contains all the output files included the Bom.csv and the Positioning.csv, not only the Gerber files.
on JLCPCB is required that the ZIP contains only the Gerber and the other 2 ones are uploaded separately.
Uploading the ZIP with all the files in it (included the CSV) doesn't bring any benefit.

**Comment by bennymeg** [comment]
True, but I thought it is a good idea to include then anyways so it will be easy to distribute the entire artifact (i.e., to client).
