### ISSUE TITLE
Please rename it JLCPCB ToolKit

### ISSUE THREAD

**Issue by tormyvancool** [bennymeg/JLC-Plugin-for-KiCad#26]
Just for a better recognition, instead of to call it Fabrication Toolkit, pleas erename it into JLCPCB ToolKit.
All the other plugins (included PCBWay) are clearly identified.
Unfortunately this, it isn't.

Just the variable " self.name = "JLCPCB Toolkit""  

thank you

**Comment by bennymeg** [comment]
It's not possible, JLC PCB (and kicad developers) do not allow that.
