### ISSUE TITLE
Column headers/order

### ISSUE THREAD

**Issue by LPG2CV** [bennymeg/JLC-Plugin-for-KiCad#28]
Probably my setup, but column headers are incorrect (not being renamed), and columns not in correct order!

I installed  the Addin. refreshed addins, and clicked on the icon that appeared. Is there something else I should be doing?

**Comment by LPG2CV** [comment]
I'm still having an issue with this!
Any thoughts anyone please. :)

**Comment by bennymeg** [comment]
Try the latest release a see if the problem persists

**Comment by LPG2CV** [comment]
Problem still persists :(

Is there anything I can do to help resolve this?

**Comment by bennymeg** [comment]
Please attach the top couple of lines of the generated BOM
Also, please provide some additional information about your system (OS, kicad version, plugin version etc.)

**Comment by LPG2CV** [comment]
Thanks :)

I have the latest version of your plugin

![image](https://user-images.githubusercontent.com/30417726/211170501-37004ee3-4a3c-4327-8e4f-7861c6743a3f.png)


Application: KiCad (64-bit)

Version: (6.0.7), release build

Libraries:
	wxWidgets 3.1.7
	libcurl/7.83.1-DEV Schannel zlib/1.2.12

Platform: Windows 10 (build 19045), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jul 26 2022 02:49:38
	wxWidgets: 3.1.7 (wchar_t,wx containers)
	Boost: 1.79.0
	OCC: 7.6.0
	Curl: 7.83.1-DEV
	ngspice: 37
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
[positions.csv](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/10367198/positions.csv)
[bom.csv](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/10367199/bom.csv)

**Comment by bennymeg** [comment]
Everything seems to work fine.
I also uploaded them to JLC to verify they work
probably just a viewing problem

**Comment by LPG2CV** [comment]
It was when I uploaded to their site and was processing towards paying that the issue came up. I contacted the help desk and they advised the bom was incorrect. :)

So a little investigation on my part showed up they are being generated that way.

**Comment by LPG2CV** [comment]
It must be the way I am set up :)
