### ISSUE TITLE
Plot options not setting "substract soldermask from silkscreen"

### ISSUE THREAD

**Issue by kiu** [bennymeg/JLC-Plugin-for-KiCad#29]
So far I manually created my gerber files for JLC based on this: https://support.jlcpcb.com/article/194-how-to-generate-gerber-and-drill-files-in-kicad-6

JLC recommends to enable "Substract soldermask from silkscreen" which I sometimes rely on due to "background art" bleeding into pads.

Is there a reason why you are not setting this?

https://github.com/bennymeg/JLC-Plugin-for-KiCad/blob/master/plugins/process.py#L32
`plot_options.SetSubtractMaskFromSilk(False)`

**Comment by bennymeg** [comment]
They probably updated their recommendation.
I will fix it in the next release (you can submit a PR if you wish =]).
Thanks for letting me know.
