### ISSUE TITLE
404 Error While Updating JLC Library

### ISSUE THREAD

**Issue by therealergo** [bennymeg/JLC-Plugin-for-KiCad#30]
When I attempt to update the local JLCPCB parts library by clicking the "Update library" button, I get an error popup saying "Failed to download the JLCPCB database CSV, error code 404". This has previously worked for me, and I can't think of anything that's changed on my end that could cause this. This is with Windows 10, KiCAD 6.0.9, and plugin version 1.2.0.

![image](https://user-images.githubusercontent.com/3515959/210038314-e13396c1-55c9-4535-87cb-eb51ed1bc12d.png)

Happy to run any tests to figure out what's going on here.

**Comment by bennymeg** [comment]
I'm not sure where you are getting this error, but I don't think it had to do with our plugin.
We are not related to JLCPCB parts library (I am not sure what that is).
Infact, we are not connecting to any JLC PCB infrastructure at all.
