### ISSUE TITLE
JLC Rotation Offset different on back of PCB

### ISSUE THREAD

**Issue by revk** [bennymeg/JLC-Plugin-for-KiCad#33]
I don't know if JLCPCB do something unusual here, but I have parts with an JLC Rotation offset which work correctly on the front of the PCB but wrong on the back. E.g. one that needed +90 on front needed -90 on back, and similarly one was 0 and 180. Does the rotation offset need adjusting when used on back of board?

As I am including the JLC Rotation Offset in my parts template it would help if I did not have to adjust this per side.

By the way, this is an awesome and useful plugin. Well done.

**Comment by bennymeg** [comment]
I meant it would be confusing for user if so of the offset they defined will be altered.
I understand the issue, but I do not have an idea how to solve it properly.

**Comment by revk** [comment]
Fair point.

Maybe a differently named offset setting that does this to match how JLC do it, which is the new setting, with the old one deprecated but retained for backward compatibility.
