### ISSUE TITLE
The designator with C and R can't be merged in the bom in KiCAD 7.0

### ISSUE THREAD

**Issue by xzf16** [bennymeg/JLC-Plugin-for-KiCad#38]
Hi, 

When I using the toolkit in KiCAD 7.0, I found that the component whose designators start with C and R can't be merged although they have the same footpirnt and values.

Here is an example:
[bom.csv](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/10800552/bom.csv)

**Comment by xzf16** [comment]
Sorry, I found that you have solved this issue but has not been released yet.

**Comment by bennymeg** [comment]
Added a local release with the fix
