### ISSUE TITLE
Place JLC in title of KiCad plugin 

### ISSUE THREAD

**Issue by itskando** [bennymeg/JLC-Plugin-for-KiCad#43]
![image](https://user-images.githubusercontent.com/15063663/225939850-16cc5f49-eaf9-45e9-8d5c-5bd0b3bdc552.png)

**Comment by itskando** [comment]
Possibly consider adding logo as well.

**Comment by itskando** [comment]
Oh. Lame. 

Thanks for providing support and for the response —

**Comment by tormyvancool** [comment]
> Hi, Unfortunately, this is not permitted by both JLC PCB and KiCad developers. It seems that JLC want their users to use `easyeda` rather than KiCad. You can reach them for more information.

Well for who have ade this plugin: it's permitted: https://github.com/Bouni/kicad-jlcpcb-tools so I think it will be for you as well. Moreover the icon yu used, it's very similar (almost identical) to the one of the plugin "Replicate Layout"

**Comment by itskando** [comment]
Added additional image for clarity.

**Comment by itskando** [comment]
Could the title in the menu be changed more cheekily?

CLJ Plug-In For KiCad
