### ISSUE TITLE
Rotation wrong on bottom of board for JLCPCB

### ISSUE THREAD

**Issue by revk** [bennymeg/JLC-Plugin-for-KiCad#51]
The `positions.csv` is generated with Mid X, Mid Y, and Rotation "_as viewed from top_". This seems to be how KiCad works.

E.g. this is two 0603 resistors with rotation of 10 degrees.

<img width="1220" alt="Screenshot 2023-04-13 at 10 20 07" src="https://user-images.githubusercontent.com/996983/231714653-9e8663db-50c4-4548-953d-dc0cefc425cb.png">

KiCad 3D view shows clearly.

![a](https://user-images.githubusercontent.com/996983/231717125-146f18c6-d557-4c31-a203-6d41e7088998.png)
![b](https://user-images.githubusercontent.com/996983/231717141-f54b7f47-d59a-4610-99ad-63b4494e8d40.png)

As you can see the 10 degree rotations is "_as viewed from top_".

The `positions.csv` file looks like this... showing both as 10 degrees.

```
Designator,Mid X,Mid Y,Rotation,Layer
R1,3.0,5.0,10.0,top
R2,7.0,5.0,10.0,bottom
```

However, when loaded on JLCPCB the rotation on the bottom is wrong, e.g

<img width="999" alt="Screenshot 2023-04-13 at 10 13 08" src="https://user-images.githubusercontent.com/996983/231714907-216a7da1-4787-4aba-ae6d-388905272a50.png">
<img width="1003" alt="Screenshot 2023-04-13 at 10 13 18" src="https://user-images.githubusercontent.com/996983/231714935-b3fc4d4a-7a7b-4662-b373-83dc269f6863.png">

Clearly JLC are expecting the rotation "_as viewed from above the component_".

The `positions.csv` file needed is

```
Designator,Mid X,Mid Y,Rotation,Layer
R1,3.0,5.0,10.0,top
R2,7.0,5.0,350.0,bottom
```

This works as expected.

<img width="1003" alt="Screenshot 2023-04-13 at 10 16 40" src="https://user-images.githubusercontent.com/996983/231716904-35876954-916e-4583-9895-484973242030.png">

If a rotation offset is applied, it works as you would expect, just added to the rotation, and could be used as a -20 offset to "fix" the bottom layer in this case, but that only works if rotated 10 degrees. Rotate 20 and you need to change the `JLCPCB Rotation Offset` to -40 to fix it. This is why the offsets seemed not to work. It is not the offset that is wrong, it is that **all** rotations on the back of the board need to be inverted, so as to be "_as viewed from above the component_" and not "_as viewed from top_" in the way KiCad works.

I think if the `JLCPCB Rotation Offset` is applied first, when present, to correct for whatever orientation JLC have used for the part, but then all bottom side rotations are inverted, it will be consistent and avoid having to tweak the back of every board.

This was obviously not obvious as rotations 0, and 180 did not show the problem, and 90 or 270 only showed on polarised components. But even a simple 0603, with no need for any rotation offset, breaks if placed at 45 degrees, so I think this is a definite bug, and should be fixed even with the backwards compatibility issues it would cause.

**Comment by bennymeg** [comment]
Thank you for contributing!
