### ISSUE TITLE
Part numbers ignored in KiCAD 7.0.2

### ISSUE THREAD

**Issue by stormyweathers** [bennymeg/JLC-Plugin-for-KiCad#57]
I've tried using `LCSC Part #`, `LCSC`, and `MPN` as fields, but the plugin appears to be ignoring these and leaving the part number blank in the output `bom.csv`.  

I'm using KiCAD 7.0.2

**Comment by uwu64** [comment]
Same issue here on 7.0.1

**Comment by nitrousnrg** [comment]
Same issue on 7.02

**Comment by nitrousnrg** [comment]
I take that back. The fields were in the schematic, but I didn't sync the schematic fields to the pcb layout fields. After sync with F8 it produced the correct file.

**Comment by stormyweathers** [comment]
This issue is still a problem for me.  There are no LCSC part numbers populated in the BOM output.

I've verified that I'm synching board and schematic before output. 

`KiCAD 7.05`,  `JLC-Plugin 3.0.0`
