### ISSUE TITLE
Merging on Plugin Tool

### ISSUE THREAD

**Issue by tormyvancool** [bennymeg/JLC-Plugin-for-KiCad#6]
Hi Benny a super thank you for this update.

PLease remember to merge it as here described by der.ule because otherwise it's not available on the Plugin Tool.
Indeed I updated it manually

[https://forum.kicad.info/t/jlcpcb-fabrication-toolkit-how-to-save-in-the-project-dir/36684/23](url)

**Comment by bennymeg** [comment]
It is waiting for approval from the KiCad developers.
You can check the progress here: https://gitlab.com/kicad/addons/metadata/-/merge_requests/105

Please DO NOT open a new issue for that.
