### ISSUE TITLE
Running the plugin creates a DRC error.

### ISSUE THREAD

**Issue by zapta** [bennymeg/JLC-Plugin-for-KiCad#65]
Using Kicad 7.0.5 on Windows and plugin version 2.2.0. It's a very strange behavior:

1. In the PCB editor with all DRC's cleaned.
2. Running the Fabrication Toolkit plugin to generate production files.
3. Running the DRC verification now give an error, as if the plugin mutated something.

The issue is very consistent, and I could not see any change in the pcb file if I save it again. 

Clear DRC
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/2184769/85cf008c-d764-4d91-a3f6-b456d23ad62b)

After running the plugin, a single error appears:
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/2184769/d63d6cb6-90a3-4491-950d-7a1073097904)
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/2184769/b2560314-1003-4df7-b32c-e02f3e582cdc)

**Comment by Fisheiyy** [comment]
i doubt the plugin is doing anything, but all that error is saying is that the footprint doesnt match whats in the library, ie its not the same as what kicad knows it as

**Comment by zapta** [comment]
That's correct, the question is why running the plugin creates this error
condition? It didn't exist before I run the plugin.

**Comment by Fisheiyy** [comment]
Im not sure this is a problem with the plugin, let alone something that can be fixed since it doesnt do anything but read the pcb and schematic data not modify it, then produce output files for production
