### ISSUE TITLE
Please check zones are filled

### ISSUE THREAD

**Issue by obaterspok** [bennymeg/JLC-Plugin-for-KiCad#73]
Hi,

When exporting fabrication outputs from KiCad it checks that all zones are filled and issue below warning if that is not the case:
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/5311823/e2453d8a-c8d2-4e4e-bae4-9ac576f57415)

It would be nice if this plugin could do the same. I just noticed because I had a board come back where I had moved a component without refilling the zone :(

-- john

**Comment by bennymeg** [comment]
Sounds good, but I not sure how to check if the board if refilled after a change at the moment

**Comment by Fisheiyy** [comment]
This would be nice, but im not sure how you would implement it, perhaps try enabling the auto zone refill in your settings?
