### ISSUE TITLE
Wrong components alignement on JLC

### ISSUE THREAD

**Issue by tormyvancool** [bennymeg/JLC-Plugin-for-KiCad#78]
Dear

I notice that each time I upload the list to JLC, something wrogn appears regarding the components' alignemnt.
For isntance: here the diodes:

![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/32305535/ed3eef5b-2bad-4443-826f-f14a66e4dd14)

But it occurs also with Transistors and ICs. the rotation angle is always wrong.
OK JLC will corect by hands, but aside this, the files are getting wrong positioning I see.

EDIT: I opened also a topic here: https://forum.kicad.info/t/wrong-components-alignement-for-jlcpcb-not-clue-if-due-kicad-or-due-the-script/43772

**Comment by bennymeg** [comment]
That's probably because kicad footprints and jlc footprints are not always aligned the same.
Please check that the problem does not exist when you export your pcb without the plugin.

**Comment by tormyvancool** [comment]
> 

Right, good point. I tried now. Yes the result is the same. Wrong exactly as for the plugin

**Comment by bennymeg** [comment]
That's way we have added option to fix the orientation for each part. we are working on implementing some automatic adjustments for some common parts, but we will never be able to fix all the misalignments that exists, it will be needed to be done manually with the options we provide.

**Comment by bennymeg** [comment]
We provide configurable options.
Please read the readme file.

**Comment by blaggacao** [comment]
I wrote o LCSC support and asked them if they could add a orientation source of truth in their API, in a case of unexpected pragmatism, someone from their team might actually reach out. (or not 🤷 )
