### ISSUE TITLE
'PLOT_CONTROLLER' object has no attribute 'PlotLayers'

### ISSUE THREAD

**Issue by NNNILabs** [bennymeg/JLC-Plugin-for-KiCad#80]
Upon pressing the button in Pcbnew, I get an error that says 'PLOT_CONTROLLER' object has no attribute 'PlotLayers'. I tried uninstalling and reinstalling the plugin, but I cannot seem to find a solution to this problem.

**Comment by eschmitty** [comment]
I am having the same issue. It was working fine yesterday and nothing has changed since then. 
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/30362930/b982a839-c9fd-4330-a6f0-a8eae747e976)

**Comment by NNNILabs** [comment]
I was able to fix it by updating KiCAD to the latest stable release.

**Comment by eschmitty** [comment]
that worked, thank you!
