### ISSUE TITLE
Error: 'PLOT_CONTROLLER' object has no attribute 'PlotLayers'

### ISSUE THREAD

**Issue by evanic14** [bennymeg/JLC-Plugin-for-KiCad#83]
Your plugin has been working fine on W10 (I used it about two weeks ago with no issues whatsoever).
Last week I upgraded to W11 and since then it gives me this error when I press the generate button in the PCB editor.
I don't know if W11 has anything to do with it but it is pretty suspicious.

I tried launching KiCad in administrator mode and uninstalled the plugin but this wouldn't work either.
I'm using windows version:  22H2
KiCad version: 7.0.0
Plugin version: 3.0.0

**Comment by bennymeg** [comment]
See #80
