### ISSUE TITLE
'FOOTPRINT'  object has no attribute 'HasProperty'

### ISSUE THREAD

**Issue by RealET** [bennymeg/JLC-Plugin-for-KiCad#84]
On Linux, Kicad 7.99.

When trying to trigger the plugin, it states: `'FOOTPRINT'  object has no attribute 'HasProperty'` and does not generate any files.

**Comment by RealET** [comment]
Ah gotcha, sorry about that.  I accidentally updated and now my projects are not backward-compatible.

**Comment by bennymeg** [comment]
X.99 version are essentially nightly development versions for the next release of KiCad.
Unfortunately, I do not have enough time to support it ahead of time.
But if someone would be able to contribute a non-breaking fix for that issue, I'll be happy to merge it.
