### ISSUE TITLE
Add prompt to re-fill pours if the pours are out of date

### ISSUE THREAD

**Issue by DeflateAwning** [bennymeg/JLC-Plugin-for-KiCad#86]
Just did an off and ordered a PCB with out-of-date pours. Some of the traces are shorted to the ground pour, because I moved the traces into the pour last minute and then didn't re-pour. 

My bad.

Would've been nice if it prompted with a warning saying that the pours are out-of-date. This is a feature in the regular Gerber exporter, iirc.

If this feature was already added, I wasn't on a late enough version (but am not sure what version I was on).

**Comment by obaterspok** [comment]
This has been fixed to always perform a re-fill prior to an export

Duplicate of #73

**Comment by bennymeg** [comment]
I'm sorry to hear that.
As @obaterspok mentioned, it had been fixed (by him [thanks for the contribution]) in v3.0.2.

**Comment by DeflateAwning** [comment]
Thank you!
