### ISSUE TITLE
Error when executing the plugin

### ISSUE THREAD

**Issue by marcpiulachs** [bennymeg/JLC-Plugin-for-KiCad#88]
I'm getting the following error 'PLOT_CONTROLLER' object has no attribute 'PlotLayers' on Kicad 7.0.0 

I'm not sure if it's related to my particular setup or it's related to Kicad 7, I have been trying old projects where I used this same plugin and they are also failing

**Comment by makuser** [comment]
KiCad 7.0.0 does not have the PlotLayers method, you need to upgrade to a newer patch version than 7.0.1.

At least there's no need for you to fully migrate from a major version like from 6.X.Y to 7.X.Y, as you already are on the 7 major version...

**Comment by marcpiulachs** [comment]
It was solved updating the KiCad version as you mentioned, thanks
