### ISSUE TITLE
Semantic error

### ISSUE THREAD

**Issue by globalcitizen** [bennymeg/JLC-Plugin-for-KiCad#9]
**MPN** mans **Manufacturer Part Number**.

This is a different meaning to distributor part numbers, such as **LCSC Part #** (recently encouraged by JLC to be renamed to **JLCPCB Part #**).

However, in your plugin, about which I learned after watching [this MCH video](https://media.ccc.de/v/mch2022-332-the-tooling-ecosystem-that-adds-joy-to-kicad) seems to be positioned as the de-facto predominant interface for JLC for Kicad 6, I would recommend best practice approach, ie.

- Do not call distributor part numbers 'MPN'
- Realise that these fields represent different information and may both be present
- In a situation in which more than one field is present, clarify in documentation which fields will be used in which order.

Given that so many people come to KiCad as a first EDA experience I believe it is extra important to get this right.

As I have not yet upgraded to KiCad 6.x from KiCad 5.1.x (mostly due to the huge amount of custom tooling in use) I regret that I do not have a test environment or familiarity to provide a pull request myself.

**Comment by bennymeg** [comment]
Thank you for letting me know,
I guess I could try and search for all the unique fields first and if they are not preset, fallback to the MPN field. (even due that they are means different things this might help with the component selection).
Does the sounds good for you?

**Comment by bennymeg** [comment]
Ended up implementing it the following way (for simplicity):

- Primary fields: `LCSC Part #`, `JLCPCB Part #`

- Failing the above (correct) fields, the fields `LCSC` or `JLC` in capitals could be used.

- Failing any of those, the field `MPN` in capitals could be used.

- Following those, the fields `MPN in any other case` could be used.
