### ISSUE TITLE
output_path characters not normalized

### ISSUE THREAD

**Issue by Fisheiyy** [bennymeg/JLC-Plugin-for-KiCad#92]
when exporting files with a odd characters such as ^ it will pass to the name of the output folder and the name of the gerber archive which causes issues when uploading to JLC for production

KiCad 7.0, Plugin 3.0.0

**Comment by bennymeg** [comment]
This should be handled.
Please provide an example.

**Comment by Fisheiyy** [comment]
> This should be handled. Please provide an example.

I havent tested with any other special characters, but the ^ one gets past the current normalization that is happening so it causes an error when uploaded to JLC unless I manually remove the ^
![image](https://github.com/bennymeg/JLC-Plugin-for-KiCad/assets/54205282/06f8bb90-a3ae-4624-9871-237d09dce6f6)

**Comment by bennymeg** [comment]
I just saw you are using v3.0.0
This was fixed at v3.0.2 (currently in prerelease).

- (#85)
