### ISSUE TITLE
Rotation and Layer are reversed

### ISSUE THREAD

**Issue by GW8RDI** [bennymeg/JLC-Plugin-for-KiCad#98]
Trying to upload the files to JLCPCB but it says the CPL file isn't correct. Checking the JLCPCB sample of the format the layer and rotation columns are reversed.

**Comment by bennymeg** [comment]
Reverse them manually an check if it fix the problem.

**Comment by GW8RDI** [comment]
Do you think it's a KiCAD maintenance issue with the 3D models, some models are okay, others rotated almost at random.

**Comment by bennymeg** [comment]
Are you talking about the columns or the rotation?
The column order should not matter.
The rotation of KiCad components and JLC components do not always match and needed to be manually adjusted.
We are working to improve the default rotations for some common components.
