### ISSUE TITLE
Enhancement Request: Update Part Values and JLC Part IDs on Subsequent Exports

### ISSUE THREAD

**Issue by wimbuhTri** [bennymeg/JLC-Plugin-for-KiCad#99]
Hello,
Firstly, I would like to express my gratitude for the fantastic KiCad plugin you've developed for exporting manufacturing files. It has been an invaluable tool for my projects.

I've noticed a minor inconvenience that I believe could enhance the usability of the plugin even further. When exporting a revised design by clicking the plugin for the second time, the part values and JLC part IDs do not get updated on the Bill of Materials (BOM) and Position files. This results in the need for manual adjustments after each revision, which can be time-consuming.

I understand that software development is a complex process, and I truly appreciate the effort you've put into creating and maintaining this plugin. If possible, could you consider implementing a feature that ensures the automatic update of part values and JLC part IDs when the plugin is used for subsequent exports? This enhancement would streamline the workflow and contribute to a more seamless user experience.

Thank you once again for your dedication to the KiCad community. I look forward to the continued improvement of this excellent plugin.

**Comment by bennymeg** [comment]
I think the issue is that you need to sync your board with the schematic after you update these values.
Could you try it and let me know?
